// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Codex CLI adapter - pure TOML config artifact generator (Slice 1).

import { buildAuthoritativeAllowlist } from "./allowlist.js";
import {
  CODEX_REQUIRED_AUTHORITATIVE_TOOLS,
  type CodexConfigOverride,
  type CodexMcpBridgePlan,
  type CodexMcpBridgePlanInput,
  type CodexMcpConfigArtifact,
  type CodexMcpConfigInput,
  DREAMGRAPH_AUTHORITATIVE_SERVER_NAME,
} from "./types.js";

const CODEX_MCP_APPROVAL_MODE = "approve";

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlArray(values: readonly string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

function codexMcpEnvTableLines(env: Readonly<Record<string, string>>): readonly string[] {
  const lines = [
    "",
    `[mcp_servers.${DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}.env]`,
  ];
  for (const key of Object.keys(env).sort()) {
    lines.push(`${key} = ${tomlString(env[key] ?? "")}`);
  }
  return Object.freeze(lines);
}

function codexMcpToolApprovalSections(allowlist: readonly string[]): readonly string[] {
  const lines: string[] = [];
  for (const tool of allowlist) {
    lines.push(
      "",
      `[mcp_servers.${DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}.tools.${tool}]`,
      `approval_mode = ${tomlString(CODEX_MCP_APPROVAL_MODE)}`,
    );
  }
  return Object.freeze(lines);
}

export function buildCodexMcpConfig(
  input: CodexMcpConfigInput,
): CodexMcpConfigArtifact {
  validateCodexMcpConfigInput(input);

  const env = codexMcpEnv(input);
  const content = [
    "# Generated by DreamGraph for an isolated Codex CLI run.",
    "# Do not copy this file into the user's persistent CODEX_HOME.",
    `[mcp_servers.${DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}]`,
    `command = ${tomlString(input.dreamgraphCommand)}`,
    `args = ${tomlArray(input.dreamgraphArgs)}`,
    `trust_level = ${tomlString("trusted")}`,
    `disabled_tools = ${tomlArray([])}`,
    `default_tools_enabled = true`,
    `default_tools_approval_mode = ${tomlString(CODEX_MCP_APPROVAL_MODE)}`,
    ...codexMcpEnvTableLines(env),
    ...codexMcpToolApprovalSections(input.allowlist),
    "",
  ].join("\n");

  return {
    filename: "config.toml",
    content,
    metadata: {
      runId: input.runId,
      authoritativeServer: DREAMGRAPH_AUTHORITATIVE_SERVER_NAME,
      allowlist: Object.freeze([...input.allowlist]),
    },
  };
}

export function buildCodexMcpConfigOverrides(
  input: CodexMcpConfigInput,
): readonly CodexConfigOverride[] {
  validateCodexMcpConfigInput(input);
  // Codex 0.133 accepts stdio MCP `env` only as a nested TOML table in
  // config.toml, and its strict config loader rejects array-valued
  // `mcp_servers.<name>.args=[...]` overrides. Keep the bridge server as one
  // isolated config.toml definition rather than duplicating it through `-c`.
  return Object.freeze([]);
}

function validateCodexMcpConfigInput(input: CodexMcpConfigInput): void {
  if (!input.runId) {
    throw new Error("buildCodexMcpConfig: runId is required");
  }
  if (!input.transportToken) {
    throw new Error("buildCodexMcpConfig: transportToken is required");
  }
  if (!input.dreamgraphCommand) {
    throw new Error("buildCodexMcpConfig: dreamgraphCommand is required");
  }
  if (input.allowlist.length === 0) {
    throw new Error("buildCodexMcpConfig: allowlist must contain at least one tool");
  }
}

function codexMcpEnv(input: CodexMcpConfigInput): Readonly<Record<string, string>> {
  return {
    ...(input.dreamgraphEnv ?? {}),
    DREAMGRAPH_MCP_TOKEN: input.transportToken,
    DREAMGRAPH_RUN_ID: input.runId,
  };
}

export function buildCodexMcpBridgePlan(
  input: CodexMcpBridgePlanInput,
): CodexMcpBridgePlan {
  const allowlist = buildAuthoritativeAllowlist(input.liveToolNames);
  if (!allowlist.ok) {
    throw new Error(
      `buildCodexMcpBridgePlan: DreamGraph tool registry mismatch; missing required tools: ${allowlist.missingRequired.join(", ")}`,
    );
  }

  const configInput: CodexMcpConfigInput = {
    runId: input.runId,
    transportToken: input.transportToken,
    dreamgraphCommand: input.dreamgraphCommand,
    dreamgraphArgs: input.dreamgraphArgs,
    dreamgraphEnv: input.dreamgraphEnv,
    allowlist: allowlist.tools,
  };
  const config = buildCodexMcpConfig(configInput);

  return {
    allowlist,
    config,
    configOverrides: buildCodexMcpConfigOverrides(configInput),
    registry: {
      authoritativeServer: DREAMGRAPH_AUTHORITATIVE_SERVER_NAME,
      requiredTools: CODEX_REQUIRED_AUTHORITATIVE_TOOLS,
      allowedTools: allowlist.tools,
      missingRequired: allowlist.missingRequired,
    },
  };
}

export function serializeCodexMcpConfig(
  artifact: CodexMcpConfigArtifact,
): string {
  return artifact.content;
}
