"use strict";
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Codex CLI adapter - pure TOML config artifact generator (Slice 1).
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildCodexMcpConfig = buildCodexMcpConfig;
exports.buildCodexMcpConfigOverrides = buildCodexMcpConfigOverrides;
exports.buildCodexMcpBridgePlan = buildCodexMcpBridgePlan;
exports.serializeCodexMcpConfig = serializeCodexMcpConfig;
const allowlist_js_1 = require("./allowlist.js");
const types_js_1 = require("./types.js");
function tomlString(value) {
    return JSON.stringify(value);
}
function tomlArray(values) {
    return `[${values.map(tomlString).join(", ")}]`;
}
function tomlInlineTable(values) {
    const entries = Object.keys(values)
        .sort()
        .map((key) => `${key} = ${tomlString(values[key] ?? "")}`);
    return `{ ${entries.join(", ")} }`;
}
function buildCodexMcpConfig(input) {
    validateCodexMcpConfigInput(input);
    const env = codexMcpEnv(input);
    const content = [
        "# Generated by DreamGraph for an isolated Codex CLI run.",
        "# Do not copy this file into the user's persistent CODEX_HOME.",
        `[mcp_servers.${types_js_1.DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}]`,
        `command = ${tomlString(input.dreamgraphCommand)}`,
        `args = ${tomlArray(input.dreamgraphArgs)}`,
        `env = ${tomlInlineTable(env)}`,
        `default_tools_approval_mode = ${tomlString("auto")}`,
        "",
    ].join("\n");
    return {
        filename: "config.toml",
        content,
        metadata: {
            runId: input.runId,
            authoritativeServer: types_js_1.DREAMGRAPH_AUTHORITATIVE_SERVER_NAME,
            allowlist: Object.freeze([...input.allowlist]),
        },
    };
}
function buildCodexMcpConfigOverrides(input) {
    validateCodexMcpConfigInput(input);
    const env = codexMcpEnv(input);
    return Object.freeze([
        { key: `mcp_servers.${types_js_1.DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}.command`, value: tomlString(input.dreamgraphCommand) },
        { key: `mcp_servers.${types_js_1.DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}.args`, value: tomlArray(input.dreamgraphArgs) },
        { key: `mcp_servers.${types_js_1.DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}.env`, value: tomlInlineTable(env) },
        { key: `mcp_servers.${types_js_1.DREAMGRAPH_AUTHORITATIVE_SERVER_NAME}.default_tools_approval_mode`, value: tomlString("auto") },
    ]);
}
function validateCodexMcpConfigInput(input) {
    if (!input.runId) {
        throw new Error("buildCodexMcpConfig: runId is required");
    }
    if (!input.transportToken) {
        throw new Error("buildCodexMcpConfig: transportToken is required");
    }
    if (!input.dreamgraphCommand) {
        throw new Error("buildCodexMcpConfig: dreamgraphCommand is required");
    }
    if (input.allowlist.length === 0) {
        throw new Error("buildCodexMcpConfig: allowlist must contain at least one tool");
    }
}
function codexMcpEnv(input) {
    return {
        ...(input.dreamgraphEnv ?? {}),
        DREAMGRAPH_MCP_TOKEN: input.transportToken,
        DREAMGRAPH_RUN_ID: input.runId,
    };
}
function buildCodexMcpBridgePlan(input) {
    const allowlist = (0, allowlist_js_1.buildAuthoritativeAllowlist)(input.liveToolNames);
    if (!allowlist.ok) {
        throw new Error(`buildCodexMcpBridgePlan: DreamGraph tool registry mismatch; missing required tools: ${allowlist.missingRequired.join(", ")}`);
    }
    const configInput = {
        runId: input.runId,
        transportToken: input.transportToken,
        dreamgraphCommand: input.dreamgraphCommand,
        dreamgraphArgs: input.dreamgraphArgs,
        dreamgraphEnv: input.dreamgraphEnv,
        allowlist: allowlist.tools,
    };
    const config = buildCodexMcpConfig(configInput);
    return {
        allowlist,
        config,
        configOverrides: buildCodexMcpConfigOverrides(configInput),
        registry: {
            authoritativeServer: types_js_1.DREAMGRAPH_AUTHORITATIVE_SERVER_NAME,
            requiredTools: types_js_1.CODEX_REQUIRED_AUTHORITATIVE_TOOLS,
            allowedTools: allowlist.tools,
            missingRequired: allowlist.missingRequired,
        },
    };
}
function serializeCodexMcpConfig(artifact) {
    return artifact.content;
}
//# sourceMappingURL=mcp-config.js.map